# Site settings
title: chordelia - Chord material by aesthetic criteria
email: chordelia-201509@closureone.com
description: > # this means to ignore newlines until "baseurl:"
  chordelia is a tool helping composers of classical, sound based, music
  creating a raw chord material.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://https://github.com/karstengresch/chordelia" # the base hostname & protocol for your site
twitter_username: gresch
github_username:  karstengresch

# Build settings
markdown: kramdown
